push

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,12 +14,15 @@ on:
       deploy_job:
         description: "Specify which deploy job to run"
         required: true
-        default: "none"
         type: choice
         options:
-          - none
           - deploy_develop
           - deploy_main
+      deploy_branch:
+        description: "Specify which branch to deploy from (default: develop)"
+        required: false
+        default: "develop"
+        type: string
 
 jobs:
   lint_and_test:
@@ -55,7 +58,7 @@ jobs:
           echo "開発環境にデプロイ中..."
 
   main_test:
-    if: github.ref == 'refs/heads/main'
+    if: github.ref == 'refs/heads/main' && success()
     runs-on: ubuntu-latest
     needs: lint_and_test
     steps:
@@ -77,25 +80,57 @@ jobs:
         run: npm test
 
   manual_deploy_develop:
+    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_job == 'deploy_develop'
     runs-on: ubuntu-latest
     needs: lint_and_test
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
 
       - name: Deploy to Development Environment (Manual)
         run: |
-          echo "Manually deploying to Development Environment..."
+          BRANCH_NAME=${{ github.event.inputs.deploy_branch }}
+          echo "Manually deploying to Development Environment from branch ${BRANCH_NAME}..."
+
+          # リモートのブランチ情報をフェッチ
+          git fetch origin
+
+          # リモートのブランチが存在するか確認
+          if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
+            git checkout $BRANCH_NAME
+          else
+            echo "Error: Branch '${BRANCH_NAME}' does not exist on the remote."
+            exit 1
+          fi
+
           # 手動デプロイの具体的なコマンドをここに追加
 
   manual_deploy_main:
+    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_job == 'deploy_main'
     runs-on: ubuntu-latest
     needs: lint_and_test
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
 
       - name: Deploy to Production Environment (Manual)
         run: |
-          echo "Manually deploying to Production Environment..."
+          BRANCH_NAME=${{ github.event.inputs.deploy_branch }}
+          echo "Manually deploying to Production Environment from branch ${BRANCH_NAME}..."
+
+          # リモートのブランチ情報をフェッチ
+          git fetch origin
+
+          # リモートのブランチが存在するか確認
+          if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
+            git checkout $BRANCH_NAME
+          else
+            echo "Error: Branch '${BRANCH_NAME}' does not exist on the remote."
+            exit 1
+          fi
+
           # 手動デプロイの具体的なコマンドをここに追加
